language: python
python: "3.6"
    
 # don't clone more than necessary
git:
  depth: 1
    
 # Install dependencies
install:
  - pip install -r requirements.txt

script: 
  - coverage run manage.py test TELLING/tests/
  
after_success:
  - codecov