language: python

python: "3.6"

git:
  depth: 1
  
install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
