# Generated by Django 3.1.4 on 2020-12-10 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TELLING', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_chapter', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='story',
            name='categories',
        ),
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TELLING.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TELLING.story'),
        ),
    ]
