
# Generated by Django 2.2.7 on 2020-11-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]