# Generated by Django 2.2.7 on 2020-11-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0002_auto_20201103_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
    ]
