# Generated by Django 3.1 on 2020-11-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0003_auto_20201103_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]