# Generated by Django 2.2.7 on 2020-11-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0004_auto_20201108_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
