# Generated by Django 3.1 on 2020-11-24 04:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0005_auto_20201116_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='image'),
        ),
    ]
