# Generated by Django 3.1 on 2020-12-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TELLING', '0005_auto_20201201_0221'),
        ('TELLING', '0007_auto_20201124_0446'),
    ]

    operations = [
    ]
